# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41a71d5e64bc13cfd731dfaeaac86d8deae76069637633e1a7e9d327e866e79fb088c683acf6a64ff16c45541d938dd43c2a41094f55da0c2d949a7fb586f980

test:
  secret_key_base: 734bc587189ce0268d9f7daffed68dd27b23c92c869c348469d2b1fcbf2a152f435b1efdcbe36dce524819a3c489a2d68aee333000140eb7a25237ff45dfb8a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
